#!/bin/bash

# $1 - name of the board to flash
# $2 - path to the repo to flash with

function flash {

  echo $1
  echo $2

  cd $2
  sudo make "BOARD=$1" flash
}

flash $1 $2

echo 
echo "Finished script. Press a key to close this terminal..."
read -n 1 -s