#!/bin/bash

# Copyright (C) 2018 Hendrik van Essen and FU Berlin
#
# This file is subject to the terms and conditions of the GNU Lesser
# General Public License v2.1. See the file LICENSE in the top level
# directory for more details.

# $1 - name of the board to flash
# $2 - path to the repo to flash with

function flash {

    echo $1
    echo $2

    make -C "$2" "BOARD=$1" flash
}

# check if development mode
if [ $3 -eq 1 ]
then
    read -p "The flash process was requested by an extension with a development id, so the extension was not signed. Do you want to continue [Y/n]? " -r choice
    # default is yes
    choice=${choice:-y}

    if [[ $choice =~ ^[Yy]$ ]]
    then
        flash "$1" "$2"

    else
        exit 0
    fi

else
    flash "$1" "$2"
fi

echo 
echo "Finished script. Press a key to close this terminal..."
read -n 1 -s